from uuid import UUID
from typing import Optional
from modules.coins.domain.ports.coins_repository import CoinsRepositoryPort
from modules.coins.domain.entities.transaction import UserCoins, CoinTransaction
from datetime import datetime
from shared.notification.websocket_manager import notification_manager

class CoinsService:
    def __init__(self, repository: CoinsRepositoryPort):
        self.repository = repository

    async def get_balance(self, user_id: UUID) -> int:
        user_coins = await self.repository.get_user_coins(user_id)
        if not user_coins:
            # Initialize coins for new user if needed, or return 0
            return 0
        return user_coins.current_coins

    async def award_coins(
        self, 
        user_id: UUID, 
        amount: int, 
        transaction_type: str, 
        service_type: Optional[str] = None,
        reference_id: Optional[UUID] = None,
        description: Optional[str] = None
    ) -> int:
        user_coins = await self.repository.get_user_coins(user_id)
        if not user_coins:
            user_coins = UserCoins(
                user_id=user_id,
                current_coins=0,
                lifetime_earned=0,
                lifetime_spent=0
            )

        user_coins.current_coins += amount
        user_coins.lifetime_earned += amount
        user_coins.updated_at = datetime.now()
        
        updated_user_coins = await self.repository.update_user_coins(user_coins)
        
        transaction = CoinTransaction(
            id=UUID(int=0), # ID will be generated by DB or Repo
            user_id=user_id,
            amount=amount,
            balance_after=updated_user_coins.current_coins,
            transaction_type=transaction_type,
            service_type=service_type,
            reference_id=reference_id,
            description=description
        )
        await self.repository.create_transaction(transaction)
        
        # Broadcast balance update
        await notification_manager.send_personal_message(str(user_id), {
            "type": "balance_update",
            "current_coins": updated_user_coins.current_coins
        })
        
        return updated_user_coins.current_coins

    async def spend_coins(
        self, 
        user_id: UUID, 
        amount: int, 
        service_type: str,
        description: Optional[str] = None
    ) -> int:
        user_coins = await self.repository.get_user_coins(user_id)
        if not user_coins or user_coins.current_coins < amount:
            raise ValueError("Insufficient coins balance")

        user_coins.current_coins -= amount
        user_coins.lifetime_spent += amount
        user_coins.updated_at = datetime.now()
        
        updated_user_coins = await self.repository.update_user_coins(user_coins)
        
        transaction = CoinTransaction(
            id=UUID(int=0), # ID will be generated by DB or Repo
            user_id=user_id,
            amount=-amount,
            balance_after=updated_user_coins.current_coins,
            transaction_type='service',
            service_type=service_type,
            reference_id=None,
            description=description
        )
        await self.repository.create_transaction(transaction)
        
        # Broadcast balance update
        await notification_manager.send_personal_message(str(user_id), {
            "type": "balance_update",
            "current_coins": updated_user_coins.current_coins
        })
        
        return updated_user_coins.current_coins
